platform :ios, '7.1'
use_frameworks!

target 'PTRManualLayout_Example' do
  pod 'PTRManualLayout', :path => '../'

  target 'PTRManualLayout_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
